module.exports = [
    { 
        name: "Apple", 
        description: "Fresh from our Farms", 
        category:"Fruit", 
        price: 1 , 
        rating: 3, 
        description: "Product quality is important because it affects the success of the company and helps establish its reputation in customer markets.",
        weight: 1000,
        brand: "Organic Farm",
    },
    { 
        name: "Pineapple", 
        description: "Fresh from our Farms", 
        category:"Fruit", 
        price: 1 , 
        rating: 5,
        description: "Product quality is important because it affects the success of the company and helps establish its reputation in customer markets.",
        weight: 1000,
        brand: "Fruits Market",
    },
    { 
        name: "strawberry", 
        description: "Fresh from our Farms",
        category:"Fruit", 
        price: 1 , 
        rating: 3,
        description: "Product quality is important because it affects the success of the company and helps establish its reputation in customer markets.",
        weight: 1000,
        brand: "Organic Farm",
    },
    { 
        name: "Onion", 
        description: "Fresh from our Farms",
        category:"Vegetable", 
        price: 1 , 
        rating: 2,
        description: "Product quality is important because it affects the success of the company and helps establish its reputation in customer markets.",
        weight: 1000,
        brand: "Country Farm",
    },
    { 
        name: "Poteto", 
        description: "Fresh from our Farms",
        category:"Vegetable", 
        price: 1 , 
        rating: 3,
        description: "Product quality is important because it affects the success of the company and helps establish its reputation in customer markets.",
        weight: 1000,
        brand: "Organic Farm",
    },
    { 
        name: "grape", 
        description: "Fresh from our Farms",
        category:"Fruit", 
        price: 1 , 
        rating: 5,
        description: "Product quality is important because it affects the success of the company and helps establish its reputation in customer markets.",
        weight: 500,
        brand: "Fruits Market",
    },
    { 
        name: "Green peas", 
        description: "Fresh from our Farms",
        category:"Vegetable", 
        price: 1 , 
        rating: 3,
        description: "Product quality is important because it affects the success of the company and helps establish its reputation in customer markets.",
        weight: 1000,
        brand: "Organic Farm",
    },
    { 
        name: "Carrots", 
        description: "Fresh from our Farms",
        category:"Vegetable", 
        price: 1 , 
        rating: 4,
        description: "Product quality is important because it affects the success of the company and helps establish its reputation in customer markets.",
        weight: 1000,
        brand: "Country Farm",
    },
    { 
        name: "Guava", 
        description: "Fresh from our Farms", 
        category:"Fruit", 
        price: 1 , 
        rating: 3, 
        description: "Product quality is important because it affects the success of the company and helps establish its reputation in customer markets.",
        weight: 1000,
        brand: "Organic Farm",
    },
    { 
        name: "Avocado", 
        description: "Fresh from our Farms", 
        category:"Fruit", 
        price: 1 , 
        rating: 5,
        description: "Product quality is important because it affects the success of the company and helps establish its reputation in customer markets.",
        weight: 1000,
        brand: "Fruits Market",
    },
    { 
        name: "Mango", 
        description: "Fresh from our Farms",
        category:"Fruit", 
        price: 1 , 
        rating: 3,
        description: "Product quality is important because it affects the success of the company and helps establish its reputation in customer markets.",
        weight: 1000,
        brand: "Organic Farm",
    },
    { 
        name: "White Cabbage", 
        description: "Fresh from our Farms",
        category:"Vegetable", 
        price: 1 , 
        rating: 2,
        description: "Product quality is important because it affects the success of the company and helps establish its reputation in customer markets.",
        weight: 1000,
        brand: "Country Farm",
    },
    { 
        name: "Lemon", 
        description: "Fresh from our Farms",
        category:"Vegetable", 
        price: 1 , 
        rating: 3,
        description: "Product quality is important because it affects the success of the company and helps establish its reputation in customer markets.",
        weight: 1000,
        brand: "Organic Farm",
    },
    { 
        name: "Banana", 
        description: "Fresh from our Farms",
        category:"Fruit", 
        price: 1 , 
        rating: 5,
        description: "Product quality is important because it affects the success of the company and helps establish its reputation in customer markets.",
        weight: 500,
        brand: "Fruits Market",
    },
    { 
        name: "Tomato", 
        description: "Fresh from our Farms",
        category:"Vegetable", 
        price: 1 , 
        rating: 3,
        description: "Product quality is important because it affects the success of the company and helps establish its reputation in customer markets.",
        weight: 1000,
        brand: "Organic Farm",
    },
    { 
        name: "Corn", 
        description: "Fresh from our Farms",
        category:"Vegetable", 
        price: 1 , 
        rating: 4,
        description: "Product quality is important because it affects the success of the company and helps establish its reputation in customer markets.",
        weight: 1000,
        brand: "Country Farm",
    },
    { 
        name: "Mashroom", 
        description: "Fresh from our Farms",
        category:"Vegetable", 
        price: 1 , 
        rating: 3,
        description: "Product quality is important because it affects the success of the company and helps establish its reputation in customer markets.",
        weight: 1000,
        brand: "Organic Farm",
    },
    { 
        name: "Coconut", 
        description: "Fresh from our Farms",
        category:"Fruit", 
        price: 1 , 
        rating: 5,
        description: "Product quality is important because it affects the success of the company and helps establish its reputation in customer markets.",
        weight: 500,
        brand: "Fruits Market",
    },
    { 
        name: "Red Chili", 
        description: "Fresh from our Farms",
        category:"Vegetable", 
        price: 1 , 
        rating: 3,
        description: "Product quality is important because it affects the success of the company and helps establish its reputation in customer markets.",
        weight: 1000,
        brand: "Organic Farm",
    },
    { 
        name: "Pumpkin", 
        description: "Fresh from our Farms",
        category:"Vegetable", 
        price: 1 , 
        rating: 4,
        description: "Product quality is important because it affects the success of the company and helps establish its reputation in customer markets.",
        weight: 1000,
        brand: "Country Farm",
    },
];